const projectsData = [
  {
    id: 1,
    name: "Project A",
    brand: "Godrej",
    size: "2BHK",
    category: "Residential",
    subCategory: "Luxury",
  },
  {
    id: 2,
    name: "Project B",
    brand: "GLS",
    size: "3BHK",
    category: "Commercial",
    subCategory: "Affordable",
  },
  {
    id: 3,
    name: "Project C",
    brand: "DLF",
    size: "1BHK",
    category: "Residential",
    subCategory: "Luxury",
  },
  {
    id: 4,
    name: "Project D",
    brand: "Sun City",
    size: "2BHK",
    category: "Commercial",
    subCategory: "Affordable",
  },
  {
    id: 5,
    name: "Project E",
    brand: "DLF",
    size: "3BHK",
    category: "Residential",
    subCategory: "Luxury",
  },
  {
    id: 6,
    name: "Project F",
    brand: "GLS",
    size: "2BHK",
    category: "Residential",
    subCategory: "Affordable",
  },
  {
    id: 7,
    name: "Project G",
    brand: "Godrej",
    size: "1BHK",
    category: "Commercial",
    subCategory: "Luxury",
  },
];

export default projectsData;
